steps:
# Download the model to embed it into the image
#- name: 'gcr.io/cloud-builders/gsutil'
#  args: ['cp','-r', 'gs://doit-image-similarity/model', '.']
#  id: 'download-model'
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/audio-classification', '.']
#  waitFor: ['download-model']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/audio-classification']
images:
- gcr.io/$PROJECT_ID/audio-classification