main:
    params: [event]
    steps:
    - initialize:
        assign:
        - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_NUMBER")}
        - zone: us-central1
    - get_workflow_service_1:
        call: googleapis.run.v1.namespaces.services.get
        args:
            name: ${"namespaces/" + project + "/services/workflow-sevice-1"}
            location: ${zone}
        result: workflow_service_1
    - get_workflow_service_2:
        call: googleapis.run.v1.namespaces.services.get
        args:
            name: ${"namespaces/" + project + "/services/workflow-sevice-2"}
            location: ${zone}
        result: workflow_service_2
    - get_workflow_service_3:
        call: googleapis.run.v1.namespaces.services.get
        args:
            name: ${"namespaces/" + project + "/services/workflow-sevice-3"}
            location: ${zone}
        result: workflow_service_3
    - log_event:
            call: sys.log
            args:
                text: ${event}
                severity: INFO
    - extract_bucket_object:
            assign:
            - bucket: ${event.data.bucket}
            - object: ${event.data.name}
    - service_1:
        call: http.post
        args:
            url: ${workflow_service_1.status.url}
            auth:
                type: OIDC
            body:
                bucket: ${bucket} 
                object: ${object} 
        result: service_1_result
    - service_2:
        call: http.post
        args:
            url: ${workflow_service_2.status.url}
            auth:
                type: OIDC
            body:
                audio_file: ${service_1_result.body.audio_file}
        result: service_2_result
    - service_3:
        call: http.post
        args:
            url: ${workflow_service_3.status.url}
            auth:
                type: OIDC
            body:
                audio_file: ${service_1_result.body.audio_file}
                prediction: ${service_2_result.body.prediction}
                spectogram_image: ${service_1_result.body.spectogram_image} 

        result: service_3_result
    - return_result:
        return: ${service_3_result.body}