steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/workflow-sevice-1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/workflow-sevice-1']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'workflow-sevice-1', '--image', 'gcr.io/$PROJECT_ID/workflow-sevice-1', '--service-account', 'workflow-poc@$PROJECT_ID.iam.gserviceaccount.com', '--memory', '1G', '--region', 'us-central1', '--platform', 'managed', '--update-env-vars', 'PROJECT_ID=$PROJECT_ID']
images:
- gcr.io/$PROJECT_ID/workflow-sevice-1